from twilio.twiml.voice_response import VoiceResponse
from flask import Response

def a():
    return "dit is de adventureapp"

def startscript():
    response = VoiceResponse()
    response.say("This is generated by the Adventure Programming Squad!", voice='woman')
    response.say("This is generated by the Adventure Programming Squad!", voice='woman')
    return str(response)
